app = "pipecat-ws-backend"
primary_region = "fra"

[build]

[env]
  PORT = "8080"
  PIPECAT_PCM_RATE = "24000"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "15s"
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "2s"


